version: '3'
services:
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
