version: "2.4"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_URL=${DB_URL}
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
