export enum ENV_CONFIG {
  EMAIL_USER = 'EMAIL_USER',
  MORALIS_API_KEY = 'MORALIS_API_KEY',
  ETHERUM_ADDRESS = 'ETHERUM_ADDRESS',
  POLYGON_ADDRESS = 'POLYGON_ADDRESS',
  EMAIL_PASS = 'EMAIL_PASS',
  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  HYPERHIRE_EMAIL = 'HYPERHIRE_EMAIL',
}

export const REDIS_CONFIG = {
  redis: {
    host: 'localhost',
    port: 6379,
  },
};
